# Get all subdirectories of a directory
function(omni_get_subdirectories parent_dir output_var)
    file(GLOB children RELATIVE ${parent_dir} ${parent_dir}/*)
    set(dirlist "")
    foreach(child ${children})
        if(IS_DIRECTORY ${parent_dir}/${child})
            string(FIND ${child} "target_" position)
            if(${position} EQUAL 0)
                if(EXISTS "${parent_dir}/${child}/CMakeLists.txt")
                    string(REPLACE "target_" "" child ${child})
                    list(APPEND dirlist ${child})
                endif()
            endif()
        endif()
    endforeach()
    set(${output_var} ${dirlist} PARENT_SCOPE)
endfunction()